import theme from "@/theme";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import { Container } from "@mui/material";
import CssBaseline from "@mui/material/CssBaseline";
import TheHeader from "@/components/TheHeader";
import TheFooter from "@/components/TheFooter";
// import "./globals.css";

export const metadata = {
  title: "Engines Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <Container disableGutters maxWidth="false">
              <TheHeader />
              <Container component="main" maxWidth="lg" sx={{ minHeight: "100dvh" }}>
                {children}
              </Container>
              <TheFooter />
            </Container>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
